#!/bin/sh
# luci-app-eventcenter: set defaults only if config doesn't exist

if [ ! -f /etc/config/eventcenter ]; then
    uci -q batch <<-EOUCI
        set eventcenter.global=eventcenter
        set eventcenter.global.enable='1'
        set eventcenter.global.log_path='/tmp/eventcenter.log'
        set eventcenter.global.log_max_lines='1000'
        set eventcenter.global.dedup_ttl='300'
        set eventcenter.global.dedup_path='/tmp/eventcenter_dedup'
        set eventcenter.global.dedup_max='500'

        set eventcenter.telegram=notifier
        set eventcenter.telegram.enable='0'
        set eventcenter.telegram.token=''
        set eventcenter.telegram.chatid=''
        set eventcenter.telegram.parse_mode='Markdown'

        set eventcenter.wechat=notifier
        set eventcenter.wechat.enable='0'
        set eventcenter.wechat.webhook=''
        set eventcenter.wechat.mention=''

        set eventcenter.bark=notifier
        set eventcenter.bark.enable='0'
        set eventcenter.bark.server='https://api.day.app'
        set eventcenter.bark.device_key=''
        set eventcenter.bark.sound='minuet'
        set eventcenter.bark.group='EventCenter'

        set eventcenter.serverchan=notifier
        set eventcenter.serverchan.enable='0'
        set eventcenter.serverchan.sendkey=''

        set eventcenter.openclash=monitor
        set eventcenter.openclash.enable='1'
        set eventcenter.openclash.paths=''
        set eventcenter.openclash.realtime='1'
        set eventcenter.openclash.debounce='5'
        set eventcenter.openclash.interval='5'

        set eventcenter.node_health=health
        set eventcenter.node_health.enable='0'
        set eventcenter.node_health.interval='5'
        set eventcenter.node_health.delay_threshold='3000'
        set eventcenter.node_health.test_url='http://www.gstatic.com/generate_204'
        set eventcenter.node_health.notify_recovery='1'
        set eventcenter.node_health.monitor_groups=''
        commit eventcenter
EOUCI
fi

# Ensure new sections exist for upgrades (won't overwrite existing)
ensure_section() {
    local _type="$1" _name="$2"
    shift 2
    if ! uci -q get "eventcenter.${_name}" >/dev/null 2>&1; then
        uci -q set "eventcenter.${_name}=${_type}"
        while [ $# -gt 0 ]; do
            uci -q set "eventcenter.${_name}.${1}=${2}"
            shift 2
        done
        uci -q commit eventcenter
    fi
}

ensure_section notifier wechat \
    enable '0' \
    webhook '' \
    mention ''

ensure_section notifier bark \
    enable '0' \
    server 'https://api.day.app' \
    device_key '' \
    sound 'minuet' \
    group 'EventCenter'

ensure_section notifier serverchan \
    enable '0' \
    sendkey ''

# Ensure interval exists on monitor section
if ! uci -q get eventcenter.@monitor[0].interval >/dev/null 2>&1; then
    uci -q set eventcenter.@monitor[0].interval='5'
    uci -q commit eventcenter
fi
