#!/bin/sh
# luci-app-eventcenter: set defaults only if config doesn't exist

if [ ! -f /etc/config/eventcenter ]; then
    uci -q batch <<-EOUCI
        set eventcenter.global=eventcenter
        set eventcenter.global.enable='1'
        set eventcenter.global.log_path='/tmp/eventcenter.log'
        set eventcenter.global.log_max_lines='1000'
        set eventcenter.global.dedup_ttl='300'
        set eventcenter.global.dedup_path='/tmp/eventcenter_dedup'
        set eventcenter.global.dedup_max='500'

        set eventcenter.telegram=notifier
        set eventcenter.telegram.enable='0'
        set eventcenter.telegram.token=''
        set eventcenter.telegram.chatid=''
        set eventcenter.telegram.parse_mode='Markdown'

        set eventcenter.wechat=notifier
        set eventcenter.wechat.enable='0'
        set eventcenter.wechat.webhook=''
        set eventcenter.wechat.mention=''

        set eventcenter.bark=notifier
        set eventcenter.bark.enable='0'
        set eventcenter.bark.server='https://api.day.app'
        set eventcenter.bark.device_key=''
        set eventcenter.bark.sound='minuet'
        set eventcenter.bark.group='EventCenter'

        set eventcenter.serverchan=notifier
        set eventcenter.serverchan.enable='0'
        set eventcenter.serverchan.sendkey=''

        set eventcenter.serverchan3=notifier
        set eventcenter.serverchan3.enable='0'
        set eventcenter.serverchan3.sendkey=''
        set eventcenter.serverchan3.uid=''

        set eventcenter.ntfy=notifier
        set eventcenter.ntfy.enable='0'
        set eventcenter.ntfy.url='https://ntfy.sh'
        set eventcenter.ntfy.topic=''
        set eventcenter.ntfy.token=''
        set eventcenter.ntfy.user=''
        set eventcenter.ntfy.pass=''
        set eventcenter.ntfy.priority='default'
        set eventcenter.ntfy.tags=''
        set eventcenter.ntfy.icon=''
        set eventcenter.ntfy.click=''

        set eventcenter.pushplus=notifier
        set eventcenter.pushplus.enable='0'
        set eventcenter.pushplus.token=''
        set eventcenter.pushplus.topic=''
        set eventcenter.pushplus.template='markdown'

        set eventcenter.openclash=monitor
        set eventcenter.openclash.enable='1'
        set eventcenter.openclash.paths=''
        set eventcenter.openclash.realtime='1'
        set eventcenter.openclash.debounce='5'
        set eventcenter.openclash.interval='5'

        set eventcenter.health=health
        set eventcenter.health.enable='0'
        set eventcenter.health.interval='5'
        set eventcenter.health.delay_threshold='3000'
        set eventcenter.health.test_url='http://www.gstatic.com/generate_204'
        set eventcenter.health.notify_recovery='1'
        set eventcenter.health.monitor_groups=''

        set eventcenter.system_health=system_health
        set eventcenter.system_health.enable='0'
        set eventcenter.system_health.interval='5'

        set eventcenter.device_monitor=device_monitor
        set eventcenter.device_monitor.enable='0'
        set eventcenter.device_monitor.interval='2'

        commit eventcenter
EOUCI
fi

# Migrate node_health -> health (old installs)
if uci -q get eventcenter.node_health >/dev/null 2>&1; then
    if ! uci -q get eventcenter.health >/dev/null 2>&1; then
        # Rename: copy all options from node_health to health
        uci -q set eventcenter.health=health
        for opt in enable interval delay_threshold test_url notify_recovery monitor_groups; do
            val=$(uci -q get "eventcenter.node_health.${opt}" 2>/dev/null)
            [ -n "$val" ] && uci -q set "eventcenter.health.${opt}=${val}"
        done
        uci -q delete eventcenter.node_health
        uci -q commit eventcenter
    fi
fi

# Ensure new sections exist for upgrades (won't overwrite existing)
ensure_section() {
    local _type="$1" _name="$2"
    shift 2
    if ! uci -q get "eventcenter.${_name}" >/dev/null 2>&1; then
        uci -q set "eventcenter.${_name}=${_type}"
        while [ $# -gt 0 ]; do
            uci -q set "eventcenter.${_name}.${1}=${2}"
            shift 2
        done
        uci -q commit eventcenter
    fi
}

ensure_section notifier wechat \
    enable '0' \
    webhook '' \
    mention ''

ensure_section notifier bark \
    enable '0' \
    server 'https://api.day.app' \
    device_key '' \
    sound 'minuet' \
    group 'EventCenter'

ensure_section notifier serverchan \
    enable '0' \
    sendkey ''

ensure_section notifier serverchan3 \
    enable '0' \
    sendkey '' \
    uid ''

ensure_section notifier ntfy \
    enable '0' \
    url 'https://ntfy.sh' \
    topic '' \
    token '' \
    user '' \
    pass '' \
    priority 'default' \
    tags '' \
    icon '' \
    click ''

ensure_section notifier pushplus \
    enable '0' \
    token '' \
    topic '' \
    template 'markdown'

ensure_section system_health system_health \
    enable '0' \
    interval '5'

ensure_section device_monitor device_monitor \
    enable '0' \
    interval '2'

# Ensure interval exists on monitor section
if ! uci -q get eventcenter.@monitor[0].interval >/dev/null 2>&1; then
    uci -q set eventcenter.@monitor[0].interval='5'
    uci -q commit eventcenter
fi
